version: '3.9'

services:
  pact-postgres:
    image: postgres
    container_name: pact_postgres_db
    ports:
      - "5432:5432"
    healthcheck:
      test: psql postgres -U postgres --command 'SELECT 1'
    env_file:
      - default.env

  broker:
    image: pactfoundation/pact-broker:latest-multi
    container_name: broker.local
    depends_on:
      pact-postgres:
        condition: service_healthy
    ports:
      - "9292:9292"
    restart: always
    env_file:
      - default.env
    healthcheck:
      test: [
        "CMD",
        "wget",
        "-q",
        "--tries=1",
        "--spider",
        "http://$$PACT_BROKER_BASIC_AUTH_USERNAME:$$PACT_BROKER_BASIC_AUTH_PASSWORD@localhost:9292/diagnostic/status/heartbeat"
      ]
      interval: 3s
      timeout: 5s
      retries: 10
      start_period: 15s

  state-app:
    container_name: state_app.local
    build: .
    ports:
      - "5001:5001"
    entrypoint: ["python3", "state_app.py"]
    # flask requires SIGINT to stop gracefully
    stop_signal: SIGINT
    env_file:
      - default.env
    volumes:
      - ./src:/app